In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import re

In [ ]:
!pip install emoji

In [ ]:
hope = pd.read_csv('/content/preprocessed_KanHopeEDI.csv', delimiter=',',header=None, names=['class','sentence']) 

In [ ]:
hope

class                                  sentence
NaN           label                                  sentence
0.0            Hope                                 Bro super
1.0        Not-Hope                         Kakka is ossm lol
2.0            Hope                           anna super anna
3.0        Not-Hope  Super bro yalka  Tik Tok stars full rost
...             ...                                       ...
7567.0     Not-Hope                            manz game yes!
7568.0  not-Kannada                     anup kulkarni... True
7569.0         Hope     ಇದು ಚರಿತ್ರೆ ಸೃಷ್ಟಿಸೊ ಅವತಾರಾ..........
7570.0         Hope            Idu cheritre shrustiso avatara
7571.0     Not-Hope                 Yen song guru...benki ASN

[7573 rows x 2 columns]

In [ ]:
!pip install ecco
import warnings
warnings.filterwarnings('ignore')

In [ ]:
!pip install -U tensorboard

In [ ]:
#text = re.sub(r'^https?:\/\/.*[\r\n]*', '', text, flags=re.MULTILINE)
import emoji
 
def preprocessing(df):
    #for text in df['sentence']:
    df['sentence'] = df['sentence'].str.replace(r'^https?:\/\/.*[\r\n]*', 'URL')
    #    text = re.sub(r'^https?:\/\/.*[\r\n]*', '', text)
    df['sentence'] = df['sentence'].str.replace(r"[+/#@&*$%:0-9]",'')
    #df['sentence'] = df['sentence']
    for i in range(len(df['sentence'])):
        df['sentence'][i] = emoji.demojize(df['sentence'][i], delimiters=(" ", " "))
    #    text = re.sub(r"[+/#@&*$%:0-9]",'',text)
    print(df)

In [ ]:
preprocessing(hope)

            class                                           sentence
0            Hope                                          Bro super
1        Not-Hope                                  Kakka is ossm lol
2            Hope                                    anna super anna
3        Not-Hope           Super bro yalka  Tik Tok stars full rost
4        Not-Hope   rolling_on_the_floor_laughing  rolling_on_the...
...           ...                                                ...
7567     Not-Hope                                     manz game yes!
7568  not-Kannada                              anup kulkarni... True
7569         Hope              ಇದು ಚರಿತ್ರೆ ಸೃಷ್ಟಿಸೊ ಅವತಾರಾ..........
7570         Hope                     Idu cheritre shrustiso avatara
7571     Not-Hope                          Yen song guru...benki ASN

[7572 rows x 2 columns]


In [ ]:
hope.head(10)

class                                           sentence
0         Hope                                          Bro super
1     Not-Hope                                  Kakka is ossm lol
2         Hope                                    anna super anna
3     Not-Hope           Super bro yalka  Tik Tok stars full rost
4     Not-Hope   rolling_on_the_floor_laughing  rolling_on_the...
5     Not-Hope  ಈ ದರಿದ್ರ ಬಡ್ಡ್ಯತವ tiktok ನೋಡಿಯೆ ನಮ್ಮ ಮೋದಿಯವರು ...
6     Not-Hope                                 ಸೂಪರ್ ಗುರು ಲೋವ್ ಯು
7  not-Kannada                                     tik tok  China
8         Hope                               Guru super guru ninu
9         Hope  Correct agi helidera super  rolling_on_the_flo...

In [ ]:
hope.to_csv('demoji_KanHopeEDI.csv')

In [ ]:
hope_new = hope[:6815]
print(hope_new.shape)
hope_new.head()

(6176, 2)


class                                           sentence
0      Hope                                          Bro super
1  Not-Hope                                  Kakka is ossm lol
2      Hope                                    anna super anna
3  Not-Hope           Super bro yalka  Tik Tok stars full rost
4  Not-Hope   rolling_on_the_floor_laughing  rolling_on_the...

In [ ]:
index_names = hope[hope['class'] == 'not-Kannada'].index
hope = hope.drop(index_names, inplace=False)

In [ ]:
hope['class'].value_counts()

Not-Hope    4064
Hope        2112
Name: class, dtype: int64

In [ ]:
labels = hope['class'].values
X_train, X_test, y_train, y_test = train_test_split(hope['sentence'], labels, test_size=0.2, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(hope['sentence'], labels, test_size=0.5, random_state=42)

In [ ]:
train = pd.DataFrame()
val = pd.DataFrame()
test = pd.DataFrame()
train['sentence'] = X_train
train['class'] = y_train
test['class'] = X_test
test['sentence'] = y_test
val['class'] = X_val
val['sentence'] = y_val

In [ ]:
train.to_csv('train_hope.csv', columns=['sentence','class'])
test.to_csv('test_hope.csv', columns=['sentence','class'])
val.to_csv('val_hope.csv', columns=['sentence','class'])

In [ ]:
train = pd.read_csv('/content/multichannelhope.csv')
#train['labels']=LabelEncoder().fit_transform(train['class'])  
train=train.drop(columns=['Unnamed: 0'])
train.head(10)

sentence  ...                                        translation
0  YouTube subscriber at list lack kooda Ella yel...  ...  YouTube Subscriber at Least Luck Reach Everywhere
1  Thu nem yogyathe ge maha vishnu hesaru ettu en...  ...      Thu Name is worthy of the name of Maha Vishnu
2                                 Super togare teppa  ...                                        Super sharp
3                                         Super song  ...                                         Super song
4              Lyrics Artha adoru Kay kaal aadsrappa  ...                   Lyrics mean adoru gay foot dance
5                                 Anna e game yavudu  ...                              Anna What's this game
6  Nanu  weaks ninda huccha agbitidini boss song ...  ...             I am crazy from Weeks to the Boss Song
7  ನಮ್ಮ ಕನ್ನಡ ಇಂಡಸ್ಟ್ರಿ ಯಾಕೆ ನಮ್ಮ ಕಲಾವಿದರನ್ನ ಕೈ ಬ...  ...                        Why our Kannada Industry ..
8  Ninyavaga hindi li nodidiyappa?? Swalpa link s...  ...  When did you see Hindi li ?? Share a little li...
9  ಚಂದನ್ ಶೆಟ್ಟಿ ಟ್ರೊಲ್ ವಿಡಿಯೋ ನೀವು ನೋಡಿ ನೆಗಡ್ಡೆ ಇ...  ...  Chandan Shetty Troll Video You See Negadre Idr...

[10 rows x 3 columns]

In [ ]:
test = pd.read_csv('/content/multichannelhope_test.csv')
#test['lables'] = LabelEncoder().fit_transform(test['class'])
test['labels'] = test['lables']
test = test.drop(columns=['Unnamed: 0', 'lables'])
test.head(10)

sentence  ... labels
0                                        Ban tik tok  ...      1
1  Avara desha dalli erodu aethu....nnHagadre Nam...  ...      1
2                                     Game name  bro  ...      1
3  ದಿಯಾ ಚಲನಚಿತ್ರ ತುಂಬಾನೇ ಚೆನ್ನಾಗಿದೆ. ಸ್ವಲ್ಪ ಪ್ರಚಾ...  ...      0
4                      Nija nija nam manegu bandidda  ...      1
5             Unlike ಮಾಡಿದವರು ರಶ್ಮಿಕಾ ಅಭಿಮಾನಿಗಳು....  ...      1
6  ಗುರು ಎಲ್ಲಿದ್ದೆ ಗುರು ಇಷ್ಟು ದಿನ rolling_on_the_f...  ...      0
7                                 Supr bro u r video  ...      1
8                Nanu film nodade ne edict aagiddene  ...      1
9       Bere level aagi ede..appata kannada haadu...  ...      0

[10 rows x 3 columns]

In [ ]:
X_train, y_train = train['translation'],train['labels']
X_test, y_test = test['translation'], test['labels']

In [ ]:
vectorizer = TfidfVectorizer(min_df=10)
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test) 

In [ ]:
test = pd.read_csv('/content/multichannelhope_test.csv')
#test['lables'] = LabelEncoder().fit_transform(test['class'])
test['labels'] = test['lables']
test = test.drop(columns=['Unnamed: 0', 'lables'])
test.head(10)

# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
model =  LogisticRegression(penalty="l2", C=0.1)
model.fit(X_train, y_train)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=3))
print(accuracy_score(y_test, y_pred))

[[ 54 174]
 [ 14 376]]
              precision    recall  f1-score   support

           0      0.794     0.237     0.365       228
           1      0.684     0.964     0.800       390

    accuracy                          0.696       618
   macro avg      0.739     0.600     0.582       618
weighted avg      0.724     0.696     0.639       618

0.6957928802588996


# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=7)
model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [ ]:
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=3))
print(accuracy_score(y_test, y_pred))

[[ 92 136]
 [ 43 347]]
              precision    recall  f1-score   support

           0      0.681     0.404     0.507       228
           1      0.718     0.890     0.795       390

    accuracy                          0.710       618
   macro avg      0.700     0.647     0.651       618
weighted avg      0.705     0.710     0.689       618

0.7103559870550162


# Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(min_samples_split=2)
model.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=3))
print(accuracy_score(y_test, y_pred))

[[113 115]
 [ 79 311]]
              precision    recall  f1-score   support

           0      0.589     0.496     0.538       228
           1      0.730     0.797     0.762       390

    accuracy                          0.686       618
   macro avg      0.659     0.647     0.650       618
weighted avg      0.678     0.686     0.680       618

0.686084142394822


# Random Forest


In [ ]:
from sklearn.ensemble import RandomForestClassifier
#y_train = offensive['class'].values
text_classifier = RandomForestClassifier()
text_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred = text_classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=3))
print(accuracy_score(y_test, y_pred))

[[111 117]
 [ 53 337]]
              precision    recall  f1-score   support

           0      0.677     0.487     0.566       228
           1      0.742     0.864     0.799       390

    accuracy                          0.725       618
   macro avg      0.710     0.675     0.682       618
weighted avg      0.718     0.725     0.713       618

0.7249190938511327


In [ ]:
y_pred = text_classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=3))
print(accuracy_score(y_test, y_pred))

[[107 121]
 [ 52 338]]
              precision    recall  f1-score   support

           0      0.673     0.469     0.553       228
           1      0.736     0.867     0.796       390

    accuracy                          0.720       618
   macro avg      0.705     0.668     0.675       618
weighted avg      0.713     0.720     0.706       618

0.7200647249190939


# Naive Bayes


In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=3))
print(accuracy_score(y_test, y_pred))

[[ 93 135]
 [ 45 345]]
              precision    recall  f1-score   support

           0      0.674     0.408     0.508       228
           1      0.719     0.885     0.793       390

    accuracy                          0.709       618
   macro avg      0.696     0.646     0.651       618
weighted avg      0.702     0.709     0.688       618

0.7087378640776699


# SVM 

In [ ]:
from sklearn.svm import LinearSVC
model = LinearSVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=3))
print(accuracy_score(y_test, y_pred))

[[116 112]
 [ 57 333]]
              precision    recall  f1-score   support

           0      0.671     0.509     0.579       228
           1      0.748     0.854     0.798       390

    accuracy                          0.727       618
   macro avg      0.709     0.681     0.688       618
weighted avg      0.720     0.727     0.717       618

0.7265372168284789


In [ ]:
from sklearn.svm import LinearSVC
model = LinearSVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=3))
print(accuracy_score(y_test, y_pred))

[[116 112]
 [ 57 333]]
              precision    recall  f1-score   support

           0      0.671     0.509     0.579       228
           1      0.748     0.854     0.798       390

    accuracy                          0.727       618
   macro avg      0.709     0.681     0.688       618
weighted avg      0.720     0.727     0.717       618

0.7265372168284789
